#pragma once

#include "flight_config.h"

// Control outputs and settings consumed by other modules. Controller internals stay in control_modes.cpp.
extern float central_pitch;
extern int channel_1_pwm, channel_2_pwm, channel_3_pwm, channel_4_pwm;
extern int channel_5_pwm, channel_6_pwm, channel_7_pwm, channel_8_pwm;
extern const int pwm_channel1_rev, pwm_channel2_rev, pwm_channel3_rev,
    pwm_channel4_rev, pwm_channel5_rev;
extern const float pwm_channel1B_trim, pwm_channel2B_trim;
extern const float pwm_channel1C_trim, pwm_channel2C_trim;
extern const float pwm_channel1D_trim, pwm_channel2D_trim;
extern const float pwm_channel1E_trim, pwm_channel2E_trim;
extern const float pwm_channel1F_trim, pwm_channel2F_trim;
extern const float pwm_channel1G_trim, pwm_channel2G_trim;
extern const float pwm_channel4_trim, pwm_channel5_trim;
extern float ailBrake_PWM;
extern float D_ele_command_PWM_FF, E_ele_command_PWM_FF;
extern float F_ele_command_PWM_FF, G_ele_command_PWM_FF;
extern FlightMode currentMode;
extern bool int_is_valid;
extern bool force_manual;
extern const float pwm_channel1_trim;
extern const float pwm_channel2_trim;
extern const float pwm_channel3B_trim;
extern const float pwm_channel3C_trim;
extern const float pwm_channel3D_trim;
extern const float pwm_channel3E_trim;
extern const float pwm_channel3F_trim;
extern const float pwm_channel3G_trim;
extern const float pwm_channel3_trim;
extern float Aail1_PWM;
extern float Aail2_PWM;
extern float Aele_PWM;
extern float Athro_PWM;
extern float Arudd_PWM;
extern float A_pitch_sp;
extern float Bail1_PWM;
extern float Bail2_PWM;
extern float B_pitch_sp;
extern float Bthro_PWM;
extern float Brudd_PWM;
extern float B_ele_command_PWM_Manual;
extern float B_ele_command_PWM_FF;
extern float Cail1_PWM;
extern float Cail2_PWM;
extern float C_pitch_sp;
extern float Cthro_PWM;
extern float Crudd_PWM;
extern float C_ele_command_PWM_Manual;
extern float C_ele_command_PWM_FF;
extern float Dail1_PWM;
extern float Dail2_PWM;
extern float D_pitch_sp;
extern float Dthro_PWM;
extern float Drudd_PWM;
extern float D_ele_command_PWM_Manual;
extern float Eail1_PWM;
extern float Eail2_PWM;
extern float E_pitch_sp;
extern float Ethro_PWM;
extern float Erudd_PWM;
extern float E_ele_command_PWM_Manual;
extern float Fail1_PWM;
extern float Fail2_PWM;
extern float F_pitch_sp;
extern float Fthro_PWM;
extern float Frudd_PWM;
extern float F_ele_command_PWM_Manual;
extern float Gail1_PWM;
extern float Gail2_PWM;
extern float G_pitch_sp;
extern float Gthro_PWM;
extern float Grudd_PWM;
extern float G_ele_command_PWM_Manual;
extern int Ail_Clp;
extern float indi_pitch_q_des_log;
extern float indi_pitch_q_filt_log;
extern float indi_pitch_dq_des_log;
extern float indi_pitch_dq_used_log;
extern float indi_pitch_delta_e_cmd_deg_log;
extern float indi_pitch_delta_e_est_deg_log;
extern float indi_pitch_pwm_cmd_log;
extern float roll_eq;
extern float thro_des;
extern float roll_des;
extern float pitch_des;
extern float yaw_des;
extern float pitch_des_local;
extern float roll_PID;
extern float pitch_PID;
extern float yaw_PID;
extern float Phiab_des;
extern float Phiab_Mea;
extern float Phiab_PID;
extern float Phiac_Mea;
extern float Phiac_PID;
extern float Phibd_Mea;
extern float Phibd_PID;
extern float Phice_Mea;
extern float Phice_PID;
extern float Phidf_Mea;
extern float Phidf_PID;
extern float Phieg_Mea;
extern float Phieg_PID;
extern float phiab;
extern float phiac;
extern float phibd;
extern float phice;
extern float phidf;
extern float phieg;
extern float Pab;
extern float Pac;
extern float Pbd;
extern float Pdf;
extern float Pce;
extern float Peg;
extern int m1_command_PWM;
extern int m2_command_PWM;
extern int m3_command_PWM;
extern int m4_command_PWM;
extern int m5_command_PWM;
extern int m6_command_PWM;
extern int s6_command_PWM;
extern int s7_command_PWM;
